name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            if ! command -v docker >/dev/null 2>&1; then
              sudo apt update
              sudo apt install -y docker.io docker-compose git
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker $USER
            fi

            if [ ! -d "speech_to_text" ]; then
              git clone https://github.com/moecrosoft/speech_to_text.git
            fi

            cd speech_to_text
            git pull origin main

            sudo docker-compose down || true
            sudo docker system prune -f
            sudo docker-compose up -d --build